baseURL = "https://amatsuzero.github.io/Leetcode/"
languageCode = "zh-CN"
title = "面试题目分析"
publishDir="../docs"
theme="hyde-y"

# Pagination
paginate = 10
paginatePath = "page"


[author]
    name = "姜振华"
    email = "jzh16s@hotmail.com"

[params]
    brand = "Daubert"
    github = "AmatsuZero"
    linkedin = "jiangzhenhua"
    facebook = "AmatsuZero"
    twitter = "AmatsuZero"
    googleAnalytics = "UA-117515369-1"
    sidebar = "left"
